/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata_css_1

import java.io.File
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertNotNull

class OcrReaderTest {

    val ocrReader = OcrReader()

    @Test
    fun `GIVEN file WHEN reading THEN return string representation`() {
        val lines = getResourceAsText("src/test/resources/ocr_input_story1.txt")

        assertNotNull(lines)
    }

    @Test
    fun `GIVEN lines WHEN tonkenizeAccounts is called THEN return lines representing accounts`() {
        val lines = getResourceAsText("src/test/resources/ocr_input_story1.txt")
        val expectedTokenAccount: List<TokenAccount> = listOf(TokenAccount(lines.take(3)))
        val actualTokenAccounts: List<TokenAccount> = ocrReader.tokenizeAccounts(lines);

        assertEquals(expectedTokenAccount, actualTokenAccounts)
    }

    private fun getResourceAsText(path: String): List<String> =
        File(path).readLines()

}
