/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kata_css_1

class OcrReader {
    fun tokenizeAccounts(lines: List<String>): List<TokenAccount> {
        return lines.chunked(4).map { TokenAccount(it.dropLast(1)) }
    }
}

fun main() {
    println(OcrReader())
}
